title: Biologen
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3680851
  brandStrength: 0.125
  lightness: 0.819149
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Biologen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4
layout_spectrum: 0
