name: Biologen
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/59b92473-9fcf-4d1a-b7ec-6c37390a506c.png
layout_spectrum: 0.64441
typography_spectrum: 0.43718
navigation:
  - name: 'Entusiasme, glede & en smule galskap'
    id: d47af01d-52ea-4603-b0bd-5674e3a90ce8
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Biologen
description: 'Entusiasme, Glede & En smule galskap'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f5666'
    - '#d0dcf2'
    - '#a7b6cd'
    - '#171c18'
    - '#9e9993'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
