name: Biologen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43436
title: Biologen
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#313131'
    - '#737373'
    - '#b5b5b5'
    - '#e1e1e1'
  brandStrength: 0.125
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
