typography_spectrum: 0.93301
color:
  brandColors:
    - '#4f5666'
    - '#d0dcf2'
    - '#a7b6cd'
    - '#171c18'
    - '#9e9993'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74124
analytics:
  google: null
  facebook: null
  twitter: null
name: Biologen
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Entusiasme, glede & en smule galskap'
    id: d47af01d-52ea-4603-b0bd-5674e3a90ce8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/59b92473-9fcf-4d1a-b7ec-6c37390a506c.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Biologen
purpose: []
