name: Biologen
favicon: null
layout_spectrum: 0.7319149
typography_spectrum: 0.43436
title: B
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#313131'
    - '#737373'
    - '#b5b5b5'
    - '#e1e1e1'
  brandStrength: 0.125
  lightness: 0.9425532
  saturation: 0.706383
  rhythmicContrast: 0.2297872
purpose: []
