name: Biologen
favicon: null
layout_spectrum: 0.20701
typography_spectrum: 0.93301
title: Biologen
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f5666'
    - '#d0dcf2'
    - '#a7b6cd'
    - '#171c18'
    - '#9e9993'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
